### PR TITLE
Add dropdown mockup

### PR DESCRIPTION
**Pull request by dionyziz**

### CODE REVIEW

**Comment by dionyziz** [comment]
screen shot 2014-05-08 at 12 09 29 pm
screen shot 2014-05-08 at 12 09 38 pm
screen shot 2014-05-08 at 11 57 51 am

**Comment by dionyziz** [comment]
mockup by @VitSalis @dionyziz

**Comment by pkakelas** [comment]
Maybe the hover could darken the whole box, where "settings" is located. If you like it this way then it LGTM

**Comment by dionyziz** [comment]
Changed to the following:

screen shot 2014-05-09 at 1 19 58 am
screen shot 2014-05-09 at 1 20 02 am

**Pull request merged**
